---
version: 3

images:
base_image:
  - name: 'registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel9:latest'
  options:
  pull_policy: missing
  tls_verify: false

  additional_build_files:
  - src: "{{ playbook_dir }}/templates/ansible.cfg.j2"
  dest: configs/ansible.cfg

  dependencies:
  python: requirements.txt
  system: bindep.txt
  galaxy: requirements.yml

  options:
  package_manager_path: /usr/bin/microdnf

  additional_build_steps:
  prepend_builder: |
    RUN microdnf install -y python3.11 python3.11-pip python3.11-devel python3.11-pyyaml \
    && ln -sf /usr/bin/python3.11 /usr/bin/python3 \
    && ln -sf /usr/lib64/pkgconfig/systemd.pc /usr/lib64/pkgconfig/libsystemd.pc \
    && ln -sf /usr/lib64/pkgconfig/systemd.pc /usr/lib64/pkgconfig/libsystemd-journal.pc \
    && python3.11 -m pip install --no-cache-dir --upgrade --ignore-installed bindep \
    && python3.11 -m ensurepip \
    && python3.11 -m pip install --upgrade pip setuptools wheel jmespath six \
    && python3.11 -m pip install --no-cache-dir --upgrade --ignore-installed ansible

  prepend_final: |
    RUN microdnf upgrade -y \
    && export PKG_CONFIG_PATH=/usr/lib64/pkgconfig \
    && python3.11 -m pip install --no-cache-dir --upgrade --ignore-installed pip setuptools wheel jmespath six \
    && python3.11 -m pip install --no-cache-dir --upgrade --ignore-installed ansible ansible-runner \
    && python3 -m pip install --no-cache-dir --upgrade --ignore-installed pip setuptools wheel jmespath six \
    && python3 -m pip install --no-cache-dir --upgrade --ignore-installed ansible ansible-runner

  append_final: |
    USER root
    RUN microdnf clean all && \
    rm -rf /var/cache/{dnf,yum} && \
    rm -rf /etc/ansible/ansible.cfg
