# NOTE: I was unable to upgrade to Python 3.11 in the RHEL 9 DE Supported environment due to compatibility
# issues with Ansible and Ansible Runner. The current setup uses Python 3.9, which is compatible with the
# required packages.
#
# This environment is based on RHEL 9 and is designed to support the execution of Ansible playbooks
# and roles in a controlled and reproducible manner.

---
version: 3

images:
base_image:
  - name: 'registry.redhat.io/ansible-automation-platform-25/de-supported-rhel9:latest'
  options:
  pull_policy: missing
  tls_verify: false

  additional_build_files:
  - src: "{{ playbook_dir }}/templates/ansible.cfg.j2"
  dest: configs/ansible.cfg

  dependencies:
  ansible_core:
  package_pip: ansible-core
  ansible_runner:
  package_pip: ansible-runner
  python: requirements.txt
  system: bindep.txt
  galaxy: requirements.yml

  options:
  package_manager_path: /usr/bin/microdnf

  additional_build_steps:
  prepend_builder: |
    RUN microdnf install -y python3.9 python3.9-pip python3.9-devel python3.9-pyyaml --setopt=tsflags=nodocs \
    && ln -sf /usr/bin/python3.9 /usr/bin/python3 \
    && python3.9 -m pip install --no-cache-dir --upgrade --ignore-installed bindep \
    && python3.9 -m ensurepip \
    && python3.9 -m pip install --upgrade pip setuptools wheel jmespath six
    # Ansible and Ansible Runner are now installed via ansible_core and ansible_runner dependencies above
  # If you need to copy from galaxy, add the following as a separate step:
    # COPY --from=galaxy /usr/share/ansible /usr/share/ansible
  prepend_final: |
    RUN microdnf upgrade -y --setopt=tsflags=nodocs

  append_final: |
    USER root
    RUN microdnf clean all && \
    rm -rf /var/cache/{dnf,yum} && \
    rm -rf /etc/ansible/ansible.cfg
